version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=trip-management-service
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trip-management-service
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - .volumes/redis:/data
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.95.0
  #   ports:
  #     - "4317:4317"
